from selenium.webdriver.common.by import By

patient_name_container = (By.ID, 'patientName')
patient_name_link = (By.CSS_SELECTOR, '#patientName > a')
patient_name_info = (By.CSS_SELECTOR, '#patientName .icon-info')
patient_info_popup = (By.ID, 'patient_info')
patient_info_popup_title = (By.TAG_NAME, 'h2')
patient_info_popup_fscreen_btn = (By.ID, 'patient_obs_fullscreen')
patient_info_fullscreen = (By.CSS_SELECTOR, '.no-scroll > .full-modal')
patient_info_fullscreen_iframe = (By.TAG_NAME, 'iframe')
patient_info_fullscreen_close = (By.ID, 'closeFullModal')
task_form = (By.ID, 'obsForm')
task_form_task_id = (By.NAME, 'taskId')
task_form_start_time = (By.ID, 'startTimestamp')
task_form_submit = (By.ID, 'submitButton')
task_form_input_field = (By.CLASS_NAME, 'obsField')
task_form_field_label = (By.CSS_SELECTOR, '.input-header > label')
task_form_field_input = (By.CSS_SELECTOR, '.input-header > input')
task_form_field_select = (By.CSS_SELECTOR, '.input-body > select')
task_form_field_errors = (By.CSS_SELECTOR, '.input-body > .errors')
task_form_field_help = (By.CSS_SELECTOR, '.input-body > .help')
confirm_submit = (
    By.CSS_SELECTOR, '#submit_observation > ul > li:nth-child(2)')
successful_submit = (By.CSS_SELECTOR, '#submit_success > h2')
related_task = (By.CSS_SELECTOR, '#submit_success > div > p')